title: <p align="center">Ridat Maulana</p>
logo: "/images/profile.png?raw=true"
description: <p align="center">
  <a href="https://www.linkedin.com/in/ridat-maulana-0a4016262">LinkedIn</a>|<a href="https://github.com/ridatMaulana">GitHub</a>
  <br><br>
  <a href="pdf/cv.pdf">Lihat Resume Saya</a>
  </p>
  <br>
  <p align="justify">
  Saya merupakan mahasiswa di salah satu kampus di Indonesia, yaitu Universitas Suryakancana Cianjur pada Fakultas Teknik dengan Program Studi Teknik Informatika. 
  </p>
  <br>
theme: jekyll-theme-minimal
 # your Google Analytics tracking ID here
