title: <p align="center">Ridat Maulana</p> # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: <p align="center"> # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/ridat-maulana-0a4016262">LinkedIn</a>|<a href="https://github.com/ridatMaulana">GitHub</a>
  <br><br>
  <a href="#">Lihat Resume Saya</a>
  </p>
  <br><br>
  Saya merupakan mahasiswa di salah satu kampus di Indonesia, yaitu Universitas Suryakancana Cianjur pada Fakultas Teknik dengan Program Studi Teknik Informatika. 
  
theme: jekyll-theme-minimal
 # your Google Analytics tracking ID here
